name: Create README from YAML

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  serve_user:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run serve_user
      run: python yaml_to_readme.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add read.md
        git commit -m "Update read.md"
        git push